### ISSUE TITLE
crashes with "Lost connection to the RPC socket"

### ISSUE THREAD

**Issue by carboncls** [ksedgwic/clboss#112] opened 2022-04-30 17:40 UTC
From time to time, in irregular intervals, CLBOSS seems to crash `lightningd`, with these errors:

`Lost connection to the RPC socket.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Rpc: read: unexpected end-of-file in RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.`

Here is what the logfile says (loglevel=info)

`2022-04-30T16:33:29.634Z **BROKEN** lightningd: Plugin for ??{"jsonrpc": "2.0", "id": 1592071, "error": {"code": -32600, "message": "Error while processing commitment_revocation: HTTPConnectionPool(host='localhost', port=9814): Read timed out. (read timeout=5)", "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 421, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 416, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/lib/python3/dist-packages/urllib3/util/retry.py\", line 400, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/lib/python3/dist-packages/six.py\", line 703, in reraise\n    raise value\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 423, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", l>
2022-04-30T16:33:32.375Z **BROKEN** lightningd: FATAL SIGNAL 6 (version v0.11.0)
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: common/daemon.c:38 (send_backtrace) 0x563a98e8472b
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: common/daemon.c:46 (crashdump) 0x563a98e8477d
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f3ac6eb20bf
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f3ac6eb203b
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f3ac6e91858
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/log.c:821 (fatal_vfmt) 0x563a98e4687e
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/log.c:829 (fatal) 0x563a98e4691d
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/plugin_hook.c:182 (plugin_hook_callback) 0x563a98e63295
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:584 (plugin_response_handle) 0x563a98e5e98f
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:690 (plugin_read_json_one) 0x563a98e6182b
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/plugin.c:735 (plugin_read_json) 0x563a98e619c9
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:59 (next_plan) 0x563a98ed1ff2
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:407 (do_plan) 0x563a98ed24bf
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: ccan/ccan/io/io.c:417 (io_ready) 0x563a98ed255c
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: ccan/ccan/io/poll.c:453 (io_loop) 0x563a98ed3ef1
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/io_loop_with_timers.c:22 (io_loop_with_timers) 0x563a98e4063f
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: lightningd/lightningd.c:1181 (main) 0x563a98e4464a
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x7f3ac6e930b2
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0x563a98e27f1d
2022-04-30T16:33:32.375Z **BROKEN** lightningd: backtrace: (null):0 ((null)) 0xffffffffffffffff`

The first *broken* line goes on ...

What's causing this? I don't have these crashes when running without CLBOSS.

**Comment by ZmnSCPxj** [comment] 2022-05-01 00:21
Use backticks three times:

    ```
    Log stuff
    ```

```
Lost connection to the RPC socket.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Rpc: read: unexpected end-of-file in RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
```

Losing connection to the RPC socket is due to C-Lightning itself dying --- when that happens, *all* plugins lose connection to the RPC socket.  CLBOSS itself, being a C++ program, will throw a C++ exception which is uncaught and which will cause termination of CLBOSS itself, but it looks like the root cause is C-Lightning crashing.

C-Lightning builtin plugins will emit the message "Lost connection to the RPC socket": https://github.com/ElementsProject/lightning/blob/6ced5558fb7c817375112072d8f670b878356ddd/plugins/libplugin.c#L693-L697
CLBOSS just prints it differently.

So the root cause is "what is crashing C-Lightning?"  From the `**BROKEN**` logs, it looks like the direct crasher is some kind of Python code.  Apperently it is attempting to contact something on port 9814 on localhost, and timing out, causing it to crash, and the crash causes the plugin to output invalid JSON, which is what C-Lightning is complaining about.

So we need the entire first `**BROKEN**` line.

This might still be the fault of CLBOSS since CLBOSS can take up quite a large amount of CPU load sometimes, on nodes with hundreds of channels.  In that case this would be a duplicate of #100

**Comment by carboncls** [comment] 2022-05-05 06:51
Thank you, and sorry for my late reply. Here is the entire line from the logs. I only have a small node with 18 channels running on a NUC.

```
**BROKEN** lightningd: Plugin for ??{"jsonrpc": "2.0", "id": 1592071, "error": {"code": -32600, "message": "Error while processing commitment_revocation: HTTPConnectionPool(host='localhost', port=9814): Read timed out. (read timeout=5)", "traceback": "Traceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 421, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 416, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nsocket.timeout: timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/requests/adapters.py\", line 439, in send\n    resp = conn.urlopen(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 719, in urlopen\n    retries = retries.increment(\n  File \"/usr/lib/python3/dist-packages/urllib3/util/retry.py\", line 400, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/lib/python3/dist-packages/six.py\", line 703, in reraise\n    raise value\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 665, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 423, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/usr/lib/python3/dist-packages/urllib3/connectionpool.py\", line 330, in _raise_timeout\n    raise ReadTimeoutError(\nurllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=9814): Read timed out. (read timeout=5)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/carlo/.local/lib/python3.8/site-packages/pyln/client/plugin.py\", line 621, in _dispatch_request\n    result = self._exec_func(method.func, request)\n  File \"/home/carlo/.local/lib/python3.8/site-packages/pyln/client/plugin.py\", line 606, in _exec_func\n    return func(*ba.args, **ba.kwargs)\n  File \"/home/carlo/.lightning/plugins/watchtower-plugin/watchtower.py\", line 417, in on_commitment_revocation\n    tower_signature, available_slots = add_appointment(\n  File \"/home/carlo/.lightning/plugins/watchtower-plugin/net/http.py\", line 16, in add_appointment\n    response = send_appointment(tower_id, tower, appointment_dict, signature)\n  File \"/home/carlo/.lightning/plugins/watchtower-plugin/net/http.py\", line 62, in send_appointment\n    response = process_post_response(post_request(data, add_appointment_endpoint, tower_id))\n  File \"/home/carlo/.lightning/plugins/watchtower-plugin/net/http.py\", line 113, in post_request\n    return requests.post(url=endpoint, json=data, timeout=5)\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 116, in post\n    return request('post', url, data=data, json=json, **kwargs)\n  File \"/usr/lib/python3/dist-packages/requests/api.py\", line 60, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 533, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python3/dist-packages/requests/sessions.py\", line 646, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python3/dist-packages/requests/adapters.py\", line 529, in send\n    raise ReadTimeout(e, request=request)\nrequests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=9814): Read timed out. (read timeout=5)\n"}}??{"jsonrpc": "2.?v??:V returned non-result response (???:V
```

Funnily enough, `lightningd` hasn't crashed since I made this report. Looking at it now, it might be Teos at fault?

**Comment by ZmnSCPxj** [comment] 2022-05-05 11:25
Yes, probably your watchtower plugin and/or the watchtower server failed, looks like, given it is `commitment_revocation`, which CLBOSS does not hook into.  Also if you have only a few dozen channels, the inefficiencies being described in #105 et al. will not trigger for you.  Looks like CLBOSS is not at fault here.  OK to close?

**Comment by carboncls** [comment] 2022-05-05 16:26
>OK to close?

yes, thank you for your help!

**Closed as completed** 2022-05-05 16:35 UTC
